### ISSUE TITLE
Migrate to WebAppSec?

### ISSUE THREAD

**Issue by hober** [w3c/webappsec-change-password-url#18]
IIRC @mikewest invited us to move this to WebAppSec at TPAC last autumn. I think that's a fine idea. Any objections or concerns?

cc @rmondello @WICG/chairs

**Comment by mikewest** [comment]
This still sounds reasonable to me!

If this is what you'd like to do, I think the WICG process is to file an "[Intent to Migrate](https://wicg.github.io/admin/intent-to-migrate.html)" issue; @dveditz or I (or y'all!) can pass it along to  to public-webappsec@ for approval. Assuming that goes the way I'd expect based on the TPAC feedback, we can publish an FPWD and get y'all on the road to REC.

_/ccing WICG chairs, who can correct me if I'm misstating things: @marcoscaceres, @yoavweiss, @cwilso, and @travisleithead_

**Comment by mikewest** [comment]
Er. I now see that you CC'd them already. Sorry about that!

**Comment by cwilso** [comment]
Really, the key here is two things:  1) a WG decision to adopt the spec (and I'd suggest, since as per the Process you need the WG's agreement to publish a FPWD, you want to do this in a WG mailing alias), and 2) someone with W3C org privileges to migrate the repo (I presume you'd want it in the W3C org, since that's where most of your specs are?) - @dontcallmedom, @plh, @sideshowbarker or @wseltzer all have appropriate privs, I think.

**Comment by hober** [comment]
Okay, I've [posted to public-webappsec](https://lists.w3.org/Archives/Public/public-webappsec/2020May/0001.html) about this.

**Comment by hober** [comment]
@mikewest, do you think WebAppSec would also be interested in taking on [Detecting the reliability of HTTP status codes](https://wicg.github.io/change-password-url/response-code-reliability.html)?

**Comment by mikewest** [comment]
> @mikewest, do you think WebAppSec would also be interested in taking on Detecting the reliability of HTTP status codes?

First I've heard of it, but it looks interesting, and is a nice compliment to the change-password-url proposal. I wonder if it needs to be completely distinct, or if it could be folded into that proposal?

Worth raising to the WG, in any event. :)

**Comment by xfq** [comment]
Can we close this now, given #30 has been merged?
